### ISSUE TITLE
Data-store refactoring

### ISSUE THREAD

**Issue by emilh91** [Milk-Enterprises/Gambot#34]
The current interface is a very basic implementation and imposes constraints on the schema itself: a single table with two columns (key and value). It seems like a needless abstraction. I will assess whether a custom LINQ provider is right for this enhancement.

**Comment by mohammedh123** [comment]
:amused:

**Comment by emilh91** [comment]
![mj-lol.gif](https://emilh.net/img/mj-lol.gif)

**Comment by emilh91** [comment]
Alrighty, what needs to be done for this? I've been out the game for a while.

**Comment by mohammedh123** [comment]
seems like a simple producer, we should probably add a prefix or something to simplify things
so usage would be something like:
gambot, math 3+3*(3*5) -> "48"
gambot, math penis -> "Sorry, $who, but I can't compute that." or some shit like that

**Comment by emilh91** [comment]
Wrong issue, you goon.

**Comment by mohammedh123** [comment]
i meant every thing i said ( ͡° ͜ʖ ͡°)

**Comment by emilh91** [comment]
KPI's have shown that this does not align with any short-term or long-term goals.
Closing this issue now without hesitation.
