### ISSUE TITLE
Hubot-style scores for things

### ISSUE THREAD

**Issue by SupernaviX** [Milk-Enterprises/Gambot#50]
* `thing++` - add a point to thing
* `++` - add a point to the most previously voted-on thing
* `thing++ for stuff` - keep track of why you gave thing points
* `thing--` - remove a point from thing
* `--` - remove a point from the most previously voted-on thing
* `thing-- for stuff` - keep track of why you removed thing points
* `gambot: top 10` - show the top 10, with a graph of points
* `gambot: score thing` - check the score for and reasons for thing

**Comment by mohammedh123** [comment]
this should be closed

**Comment by RobKellett** [comment]
agreed
